stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - configs/default.yaml
    outs:
      - data/processed/

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/processed.csv
      - configs/default.yaml
    outs:
      - data/splits/
      - models/model.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - data/splits/train.csv
      - data/splits/test.csv
      - models/model.pkl
    outs:
      - results/live/
